src/routes/main.py
import os
from flask import Blueprint,flash,render_template,url_for,session,redirect,request,jsonify,send_file
from werkzeug.security import generate_password_hash,check_password_hash
from ..extensions import mongo
from ..helper import generate_token,verify_token,create_report
from bson.objectid import ObjectId
from ..send_email import send_reset_email
import pdfkit
from ..send_email import send_report

main = Blueprint("main",__name__)

def check_login():
    """
    The function `check_login` attempts to verify if a user is logged in by checking if a user ID is
    stored in the session.
    :return: The function `check_login()` is returning a boolean value. If the `session["user_id"]` is
    not None, it will return `True`. Otherwise, it will return `False`.
    """
    try:
        if session["user_id"] is not None:
            return True
    except:
        return False

@main.route("/",methods=["GET","POST"])
def login():
    """
    This Python function handles user login authentication using Flask and MongoDB.
    :return: The code snippet provided is a Flask route function for handling login functionality. If
    the request method is POST, it checks the user credentials against the stored password in the
    database. If the credentials are correct, it sets session variables for the username and user ID and
    redirects to the dashboard. If the credentials are incorrect, it flashes a message indicating the
    issue.
    """
    if request.method == "POST":
        session.permanent=True
        regno,passwd = request.form["studRegno"],request.form["studPass"]
        if mongo.db.users.find_one({"regno":regno}):
            storedPasswd = mongo.db.users.find_one({"regno":regno})["passwd"]
            user_id = ObjectId(mongo.db.users.find_one({"regno":regno})['_id'])
            username = mongo.db.users.find_one({"regno":regno})['username']
            if check_password_hash(storedPasswd,passwd):
                session["username"] = username
                session["user_id"] = str(user_id)
                session["regno"] = regno
                return redirect(url_for('main.dashboard'))
            else:
                flash("Username or password incorrect")
        else:
            flash("Username or password doesn't exist!")
    return render_template("index.html")


@main.route("/studSignup",methods=["GET","POST"])
def signup():
    """
    The `signup` function in Python handles user registration by checking if the user already exists,
    validating password match, hashing the password, and adding the user to the database if all
    conditions are met.
    :return: The `signup()` function returns either a rendered template "signup.html" if the request
    method is not "POST", or it redirects to the "main.login" route after processing the form data if
    the request method is "POST".
    """
    if request.method == "POST":
        username,Class,regno,passwd,repasswd,email = request.form["studName"],request.form['studClass'],request.form['studRegno'],request.form['studPass'],request.form['studRePass'],request.form['studEmail']
        if not mongo.db.users.find_one({"regno":regno}):
            if passwd == repasswd:
                hashed_value = generate_password_hash(passwd,method='scrypt')
                try:
                    addUser = {"username":username,"class":Class,"regno":regno,"email":email,"passwd":hashed_value}
                    mongo.db.users.insert_one(addUser)
                    flash("Register successful!")
                    return redirect(url_for("main.login"))
                except Exception as e:
                    flash(e)
            else:
                flash("Password doesn't match!")
        else:
            flash("User already exists")
    return render_template("signup.html")

@main.route('/home',methods=["GET","POST"])
def dashboard():
    """
    The `dashboard` function checks if a user is logged in and renders the student dashboard with the
    student's name, or redirects to the login page if not logged in.
    :return: If the user is logged in, the function will return the rendered template
    'studentDashboard.html' with the student's name passed as a parameter. If the user is not logged in,
    the function will redirect to the login page.
    """
    if check_login():
        studName = session['username']
        return render_template('studentDashboard.html',studName=studName)
    else:
        return redirect(url_for('main.login'))


@main.route("/reset_request",methods=['GET', 'POST'])
def reset_request():
    """
    The `reset_request` function handles a POST request to reset a user's password by sending a reset
    email with a unique token and storing the token in the database for verification.
    :return: The function `reset_request` is returning the rendered template 'resetEmail.html'.
    """
    if request.method == "POST":
        email = request.form['resetEmail']
        user = mongo.db.users.find_one({"email":email})
        forgot_users = mongo.db.forgot_users
        if user:
            token = generate_token(userId=str(user['_id']))
            send_reset_email(userEmail=email,token=token,username=user['username'])
            flash("A link has been send to your email for password reset! click that to reset your password")
            if not forgot_users.find_one({"token":token}):
                mongo.db.forgot_users.insert_one({"token":token,"userId":user['_id']})
    return render_template('resetEmail.html')

@main.route("/verify_reset/<token>",methods=['GET', 'POST'])
def reset_password_verify(token):
    """
    The function `reset_password_verify` checks if a token is valid and redirects to the reset password
    page if it is, otherwise it displays an error message.

    :param token: The `token` parameter in the `reset_password_verify` function is used to verify the
    user's request to reset their password. The function checks if the token is valid and not expired
    before allowing the user to proceed with resetting their password
    :return: The function `reset_password_verify(token)` returns either a redirect to the
    "reset_password" route with the userId parameter if the token is verified, or it returns a message
    "<center><h1>Invalid or expired token</h1></center>" if the token is invalid or expired.
    """
    try:
        userId = mongo.db.forgot_users.find_one({'token':token})['userId']
        if userId is not None:
            try:
                if verify_token(token=token,userId=userId):
                    return redirect(url_for("main.reset_password",userId=userId))
            except:
                return "<center><h1>Invalid or expired token</h1></center>"
        else:
            return "<center><h1>Invalid or expired token</h1></center>"
    except:
        return "<center><h1>Invalid or expired token</h1></center>"

@main.route("/password_reset/<userId>",methods=['GET', 'POST'])
def reset_password(userId):
    """
    The `reset_password` function in Python handles resetting a user's password by updating it in the
    database after verifying the new password matches the confirmation.

    :param userId: The `userId` parameter in the `reset_password` function is used to identify the user
    for whom the password is being reset. It is likely an identifier, such as a unique user ID or
    username, that is used to locate the user in the database and update their password
    :return: the rendered template "resetPassword.html" with the userId parameter passed to it.
    """
    if request.method == "POST":
            passwd,repasswd = request.form['newPass'],request.form['newRePass']
            if passwd == repasswd:
                new_hashed_value = generate_password_hash(passwd,method='scrypt')
                try:
                    mongo.db.users.update_one({'_id':ObjectId(userId)},{"$set":{"passwd":new_hashed_value}})
                    flash("Password Changed!")
                    mongo.db.forgot_users.delete_many({'userId':ObjectId(userId)})
                    return redirect(url_for("main.login"))
                except Exception as e:
                    flash(e)
                    flash("Internal Error")
            else:
                flash("Password does not match!")
    return render_template("resetPassword.html",userId=userId)

@main.route("/verify_test/<testCode>",methods=['GET', 'POST'])
def verify_test(testCode):
    """
    The function `verify_test` checks if a POST request contains a specific test code in a MongoDB
    collection and returns a JSON response with a URL if the code exists.

    :param testCode: The `testCode` parameter in the `verify_test` function seems to represent a code
    that is being checked against a list of collection names in a MongoDB database. If the `testCode` is
    found in the list of collection names, the function returns a JSON response with a URL pointing to
    the
    :return: "Redirecting to test!"
    """
    if request.method == "POST":
        if testCode in mongo.db.list_collection_names():
            return jsonify({'url':f'/test/{testCode}'})
    return "Redirecting to test!"

@main.route("/logout",methods=['GET', 'POST'])
def logout():
    """
    The `logout` function removes the 'username' from the session and redirects the user to the login
    page.
    :return: The `logout` function is returning a redirect response to the "login" route of the "main"
    blueprint.
    """
    session.pop('username')
    return redirect(url_for("main.login"))

@main.route("/test/<testCode>",methods=['GET', 'POST'])
def write_test(testCode):
    """
    The `write_test` function in Python checks if a user is logged in, retrieves test questions, allows
    users to submit answers, calculates the percentage score, and stores the result in a MongoDB
    collection.

    :param testCode: The `testCode` parameter in the `write_test` function is used to identify the

src/templates/dashBase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block customCSS %}{% endblock %}
    <!-- BootStrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <!-- AJAX -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <!-- BootStrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <div class="content">
      {% for message in get_flashed_messages() %}
      {% if "successful" in message %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% else %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endif %}
    {% endfor %}
    </div>
    {% block dashContent %}
    {% endblock %}
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    {% block customJS %}{% endblock %}
</body>
</html>

src/templates/edit_user_details.html
% extends "dashBase.html" %}

{% block title %}VEC Quiz App{% endblock %}
{% block customCSS %}
<link rel="stylesheet" href="{{ url_for('static',filename='studDashboard.css') }}">
{% endblock %}

{% block dashContent %}
    <div class="sidebar">
        <div class="studBanner">
            <img src="{{ url_for('static',filename='VEC-logo.png') }}" alt="logo" class="clgLogo">
            <h6 class="studName">{{studName}}</h6>
        </div>

        <div class="d-flex justify-content-evenly">
            <input type="text" name="testCode" id="testCode" placeholder="TEST CODE" onkeydown="writeTest(this)">
            <button id="testButton" type="button" class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#staticBackdrop">Go</button>    
        </div>

        <a href="{{ url_for('main.dashboard') }}">Dash Board</a>
        <a href="{{ url_for('main.univ_exam') }}">Write University Exam</a>
        <a href="{{ url_for('main.download_prev_result') }}">Download Previous Test Results</a>
        <!-- <a href="{{ url_for('main.edit_details') }}" class="active">Edit Your Details</a> -->
        <a href="{{ url_for('main.logout') }}" class="btn btn-danger">Logout</a>
     </div>


  <div class="content">
    <h4>Edit Your Details</h4>
  <div class="alert alert-info">
    <h6>Edit the below details if its not in this format</h6>
    <ol style="font-weight: bold;">
      <li>Student Name should be ending with thier initial (example: Vishvaa K)</li>
      <li>Student should update their University Registeration No in the Registeration number field</li>
      <li>Student should update a valid email if previous one is not correct</li>
      <li>Student must be updated like this (I-CSE-A). For Mech,EIE,AUTO please mention your class as (I-MECH-A) respectively</li>
      <li>After making changes to the fields, click sumbit button only once. (Don't click that repeatedly)</li>
    </ol>
  </div>
    <div class="edit-profile shadow-lg p-3 mb-5 bg-body-tertiary rounded">
      <form action="{{ url_for('main.edit_details') }}" method="POST" id="editDetailsForm">
        <div class="avatar d-flex justify-content-center align-items-center">
          <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png" alt="" width="150" height="150" style="border-radius: 50%;">
          <div><button type="button" class="btn btn-info btn-sm">Upload</button></div>
        </div>

        <div class="d-flex justify-content-evenly align-items-center">
          <div class="form-floating mt-3" style="width: 70%;">
            <input type="text" class="form-control" id="studName" name="studName" placeholder="Student Name" autocomplete="off">
            <label for="studName">Student Name</label>
          </div>
        </div>
        
        <div class="d-flex justify-content-evenly align-items-center">
          <div class="form-floating mt-3" style="width: 70%;">
            <input type="text" class="form-control" id="studRegno" name="studRegno" placeholder="Student Regno" autocomplete="off">
            <label for="studRegno">Student Registeration No</label>
          </div>
        </div>
        <br>
        <div class="d-flex justify-content-evenly align-items-center">
          <div class="form-floating mb-3" style="width: 70%;">
            <div class="d-flex justify-content-between">
                  <div class="d-flex justify-content-sm-evenly">
                    <select class="form-select" id="year" required >
                      <option disabled selected>Year</option>
                      <option value="I">I</option>
                      <option value="II">II</option>
                      <option value="III">III</option>
                      <option value="IV">IV</option>
                    </select>
                  </div>
                  <div class="d-flex justify-content-sm-evenly">
                    <select class="form-select" name="" id="dept" required>
                      <option disabled selected>Department</option>
                      <option value="CSE">CSE</option>
                      <option value="AI&DS">AI&DS</option>
                      <option value="AUTO">AUTO</option>
                      <option value="CIVIL">CIVIL</option>
                      <option value="CSE(CS)">CSE(CS)</option>
                      <option value="EEE">EEE</option>
                      <option value="ECE">ECE</option>
                      <option value="EIE">EIE</option>
                      <option value="IT">IT</option>
                      <option value="MBA">MBA</option>
                      
                      
                    </select>
                  </div>
                  <div class="d-flex justify-content-sm-evenly">
                    <select class="form-select" name="" id="section" required>
                      <option disabled selected>Section</option>
                      <option value="A">A</option>
                      <option value="B">B</option>
                      <option value="C">C</option>
                      <option value="D">D</option>
                    </select>
                  </div>
                  <div class="d-flex justify-content-sm-evenly">
                    <button type="button" class="btn btn-warning" onclick="updateClassSec()">Update</button>
                  </div>
              </div>
          </div>
        </div>

        <div class="d-flex justify-content-evenly align-items-center">
          <div class="form-floating mt-3" style="width: 70%;">
            <input type="text" class="form-control" id="class-sec" name="studClass" placeholder="Student Class" autocomplete="off" style="text-transform: uppercase
            ;">
            <label for="class-sec">Student Class</label>
          </div>
        </div>
        <br>

        <div class="d-flex justify-content-evenly align-items-center">
          <div class="form-floating" style="width: 70%;">
            <select class="form-select form-select-lg mb-3" name="teacherName" id="teacher" aria-label="Teacher Name" required>
              <option value="Teacher Name" selected="selected" disabled>Your Teacher Name</option>
              <option value="Baskaran V">Baskaran V</option>
              <option value="Sugapriya S">Sugapriya S</option>
              <option value="Balaji A">Balaji A</option>
              <option value="Latha J">Latha J</option>
              <option value="Dhanalakshmi R">Dhanalakshmi R</option>
              <option value="Vinothkumar M">Vinothkumar M</option>
              <option value="Anand V">Anand V</option>
              <option value="Archana G.M">Archana G.M</option>
              <option value="Kirubakaran Amalraj">Kirubakaran Amalraj</option>
            </select>
            <label for="teacher">Your Teacher Name</label>
          </div>
        </div>
        <div class="d-flex justify-content-evenly align-items-center">
          <div class="form-floating mt-3" style="width: 70%;">
            <input type="email" class="form-control" id="studEmail" name="studEmail" placeholder="Student Email" autocomplete="off">
            <label for="studEmail">Student Email</label>
          </div>
        </div>
        <div class="d-flex justify-content-evenly align-items-center">
          <button type="submit" class="btn btn-success btn-lg">Submit</button>
        </div>
      </form>
    </div>

  </div>
{% endblock %}

{% block customJS %}
    <script>
      window.onload = () =>{
            const getUserDetailsUrl = "{{ url_for('main.get_user_details') }}";
            fetch(getUserDetailsUrl,{
              "method":'POST',
            }).then(response => response.json()).then(json=>{
                    document.getElementById("studName").value = json['username'];
                    document.getElementById("studRegno").value = json['regno'];
                    document.getElementById("class-sec").value = json['class'];
                    document.getElementById("studEmail").value = json['email'];
                    document.querySelector("#teacher").value = json['teacher'];
            })
      }
      updateClassSec=()=>{
          year = document.querySelector("#year").value
          dept = document.querySelector("#dept").value
          section = document.querySelector("#section").value
          classSec = `${year}-${dept}-${section}`
          document.querySelector("#class-sec").value = classSec
      }

    sendTestCode = () =>{
        var testCode = document.querySelector("#testCode").value;
        $.ajax({
            url : `/verify_test/${testCode}`,
            type:'POST',
            data: {'testCode':testCode},
            success: function(response) { 
                window.location.href = response.url;
            }
        });}


    var writeTest=(input)=>{
        if(event.key == 'Enter'){
            var testCode = input.value;
            document.querySelector('#staticBackdrop').style.display = "block";
            var confirmButton = document.querySelector("#confirmButton");
            confirmButton.addEventListener('click',function(){
            $.ajax({
                url : `/verify_test/${testCode}`,
                type:'POST',
                data: {'testCode':testCode},
                success: function(response) { 
                    window.location.href = response.url;
                }
            })
            });
        };
    }
    </script>
{% endblock %}

src/templates/index.html
{% extends "base.html" %}

{% block title %}VEC Quiz App{% endblock %}
{% block bodyContent %}

    {% for message in get_flashed_messages() %}

        {% if "successful" in message %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% else %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
    {% endfor %}

    <div class="ModelBox shadow-lg p-3 mb-5 rounded-3">
        <h3>Student Login</h3>
        <form action="{{ url_for('main.login') }}" method="POST">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="studRegno" id="floatingInput" placeholder="Your Name" required autocomplete="off">
                <label for="floatingInput">Student Registration No</label>
              </div>
              <div class="form-floating mb-3">
                <input type="password" name="studPass" class="form-control" id="floatingInput" placeholder="password" required autocomplete="off">
                <label for="floatingInput">Password</label>
              </div>
            <button type="submit" class="btn btn-lg btn-success">Login</button>
        </form>
        <a href="{{ url_for('main.signup') }}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover loginLinks ">Don't have a account? Sign up here </a><br>
        <a href="{{ url_for('main.reset_request') }}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover loginLinks "> Forgot your password?</a><br>
    </div>

{% endblock %}

src/templates/previous_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Previous Results</title>
</head>
<body>
    <form action="" method="POST" id="resultForm">
        <label for="testCode">Test Code:</label>
        <input type="text" name="testCode" autocomplete="off" required>
        <p>Welcome, {{name}} <br>
            {% if found %}
                "Found one record!"
            {% endif %}
            </p>
         
        <button type="submit" class="btn btn-success">Submit</button>
        <a href="{{ url_for('main.dashboard') }}">Back</a>
    </form>
</body>
</html>

src/templates/redirect_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Answers Recorded</title>
</head>
<body>
    <style>
        .Heading{
            background-color: #FFA33C;
            width: 100%;
            height: 40%;
            padding: 20px;
            color: black;
            font-family: 'Noto Sans';
        }
        .date-time{
            display: flex;
            flex-direction: column;
            align-items:flex-end;
            flex-wrap: wrap;
        }
        hr{
            margin: 0;
            padding: 0;
            border: 3px solid grey;
            opacity: 1;
        }
        .Student-info{
            display: flex;
            flex-wrap: wrap;
            justify-content:space-between;
            padding: 20px;
            height: 180px;
        }
        .report{
            display: flex;
            flex-wrap: wrap;
            justify-content:space-around;
            padding: 20px;
            height: 180px;
        }
        .signature{
            height: 140px;
        }
    </style>
    <div class="d-flex justify-content-center align-items-center">
        <h1> Hi {{studName}}, <br> Your Answers have been recorded! </h1>
    </div>
    <div class="d-flex justify-content-between">
        <a href="{{ url_for('main.univ_exam') }}" class="btn btn-primary btn-lg">Write another test</a>
        <a href="{{ url_for('main.logout') }}" class="btn btn-danger btn-lg" id="logout">Logout</a>
    </div>
    
</body>
</html>

src/templates/report_email_base.html
<h1>Hi {{username}},</h1>
    
<p><strong style="font-size: medium;">Your summary report for {{testCode}} is ready! Please find it attached.</strong></p>
<br>
<p style="color: rgb(245, 245, 245);">With regards,<br>
The Communicative English Team</p>

src/templates/reset_email_base.html
<h1>Hello {{username}},</h1>
    
<p><strong style="font-size: medium;">A request has been received to change the password for your VEC Quiz app account.</strong></p>
<br>
<a href="{{ url_for('main.reset_password_verify',token=reset_token,_external=True) }}" style="text-align: center;text-decoration: none;background-color: #F5811F;padding: 15px;color: white;border-radius: 5px;"><strong>Reset Password</strong></a>
    <br><br>
<p>If you did not initiate this request, please contact us immediately at communicative english lab!
</p><br>
<p style="font-style: italic;color: rgb(245, 245, 245);">Thank you,<br>
The Communicative English Team</p>


src/templates/signup.html
{% extends "base.html" %}
{% block title %}Register for VEC Quiz App{% endblock %}

{% block bodyContent %}
    {% for message in get_flashed_messages() %}
      {% if "successful" in message %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% else %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endif %}
    {% endfor %}
    <div class="ModelBox shadow-lg p-3 mb-5 rounded-3">
        <h3>Sign up for VEC Quiz App</h3>
        <form action="{{ url_for('main.signup') }}" method="POST">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="studName" id="floatingInput" placeholder="Your Name" required>
                <label for="floatingInput">Student Name (eg: Vishvaa K)</label>
              </div>
              <div class="form-floating mb-3">
                <input type="email" class="form-control" name="studEmail" id="floatingInput" placeholder="Email" required>
                <label for="floatingInput">Email Address</label>
              </div>
              <div class="form-floating mb-3">
                <div class="d-flex justify-content-between">
                  <div class="d-flex justify-content-sm-evenly">
                    <select class="form-select" id="year" required >
                      <option disabled selected>Year</option>
                      <option value="I">I</option>
                      <option value="II">II</option>
                      <option value="III">III</option>
                      <option value="IV">IV</option>
                    </select>
                  </div>
                  <div class="d-flex justify-content-sm-evenly">
                    <select class="form-select" name="" id="dept" required>
                      <option disabled selected>Department</option>
                      <option value="CSE">CSE</option>
                      <option value="AI&DS">AI&DS</option>
                      <option value="AUTO">AUTO</option>
                      <option value="CIVIL">CIVIL</option>
                      <option value="CSE(CS)">CSE(CS)</option>
                      <option value="EEE">EEE</option>
                      <option value="ECE">ECE</option>
                      <option value="EIE">EIE</option>
                      <option value="IT">IT</option>
                      <option value="MECH">MECH</option>
                      <option value="MBA">MBA</option>
                    </select>
                  </div>
                  <div class="d-flex justify-content-sm-evenly">
                    <select class="form-select" name="" id="section" required>
                      <option disabled selected>Section</option>
                      <option value="A">A</option>
                      <option value="B">B</option>
                      <option value="C">C</option>
                      <option value="D">D</option>
                    </select>
                  </div>
                  <div class="d-flex justify-content-sm-evenly">
                    <button type="button" class="btn btn-warning" onclick="updateClassSec()">Update</button>
                  </div>
                </div>
              </div>
              <div class="form-floating mb-3">
                <input type="text" style="text-transform: uppercase;" class="form-control" name="studClass" id="class-sec" placeholder="Class&Sec" required>
                <label for="class-sec">Class & Sec</label>
              </div>
              <div class="form-floating mb-3">
                <input type="text" class="form-control" name="studRegno" placeholder="Email" required>
                <label for="floatingInput">Register Number</label>
              </div>
              <div class="form-floating mb-3">
                <input type="password" class="form-control" name="studPass" id="floatingInput" placeholder="password" required>
                <label for="floatingInput">Password</label>
              </div>
              <div class="form-floating mb-3">
                <input type="password" class="form-control" name="studRePass" id="floatingInput" placeholder="password" required>
                <label for="floatingInput">Confirm Password</label>
              </div>
            <button type="submit" class="btn btn-lg btn-primary">Register</button>
        </form>
        <a href="{{ url_for('main.login') }}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover loginLinks ">Already have an account? Login here </a><br>
    </div>
{% endblock %}

{% block customJS %}
<script>

updateClassSec=()=>{
  year = document.querySelector("#year").value
  dept = document.querySelector("#dept").value
  section = document.querySelector("#section").value
  classSec = `${year}-${dept}-${section}`
  document.querySelector("#class-sec").value = classSec
}

</script>
{% endblock %}