src/routes/teacher.py
import os,tempfile
from flask import Blueprint,flash,render_template,url_for,session,redirect,request,jsonify,send_file,make_response
from werkzeug.security import generate_password_hash,check_password_hash
from ..extensions import mongo
from ..helper import generate_token,verify_token,create_report,remove_duplicates,clean_teacher_reports
from bson.objectid import ObjectId
from ..send_email import send_reset_email
import pdfkit
from ..send_email import send_report

teacher = Blueprint("teacher",__name__,url_prefix="/teacher")

def check_login():
    try:
        if session["teacherName"] is not None:
            return True
    except:
        return False

@teacher.route("/",methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        session.permanent=True
        user_email,passwd = request.form["teacherEmail"],request.form["teacherPass"]
        if mongo.db.teachers.find_one({"email":user_email}):
            user_details = mongo.db.teachers.find_one({"email":user_email})
            storedPasswd = user_details["passwd"]
            if check_password_hash(storedPasswd,passwd):
                session["teacher_id"] = str(user_details["_id"])
                session["teacherName"] = user_details["username"]
                return redirect(url_for("teacher.dashboard"))
            flash("Username or password incorrect")
        else:
            flash("Username or password doesn't exist!")
    return render_template("teacher/index.html")

@teacher.route("/signup",methods=['GET', 'POST'])
def signup():
    if request.method == "POST":
        username,email,passwd,repasswd = request.form.get("teacherName"),request.form['teacherEmail'],request.form['teacherPass'],request.form['teacherRePass']
        user = mongo.db.users
        if not user.find_one({'username':username}) and not user.find_one({'email':email}):
            if not mongo.db.teachers.find_one({"username":username}):
                if passwd == repasswd:
                    hased_value = generate_password_hash(passwd,method='scrypt')
                    try:
                        addteacher = {"username":username,
                        "email":email,
                        "passwd":hased_value}
                        mongo.db.teachers.insert_one(addteacher)
                        flash("Registered successfully!")
                        return redirect(url_for('teacher.login'))
                    except Exception as e:
                        flash(e)
                else:
                    flash("Password doesn't match!")
            else:
                flash("User is already exists")
        else:
            flash("You are a student, you can't be a teacher!")
    return render_template("teacher/signup.html")

@teacher.route('/reset_request',methods=['GET', 'POST'])
def reset_request():
    if request.method == "POST":
        email = request.form['resetEmail']
        user = mongo.db.teachers.find_one({"email":email})
        forgot_users = mongo.db.forgot_users
        if user:
            token = generate_token(userId=str(user['_id']))
            send_reset_email(userEmail=email,token=token,username=user['username'])
            flash("A link has been send to your email for password reset! click that to reset your password")
            if not forgot_users.find_one({"token":token}):
                forgot_users.insert_one({"token":token,"userId":user['_id']})
    return render_template('teacher/resetEmail.html')

@teacher.route("/verify_teacher_reset/<token>",methods=['GET', 'POST'])
def reset_teacher_password_verify(token):
    userId = mongo.db.forgot_users.find_one({'token':token})['userId']
    if userId is not None:
        try:
            if verify_token(token=token,userId=userId):
                return redirect(url_for("teacher.reset_password",userId=userId))
        except:
            return "<center><h1>Invalid or expired token</h1></center>"
    else:
        return "<center><h1>Invalid or expired token</h1></center>"

@teacher.route("/password_reset/<userId>",methods=['GET', 'POST'])
def reset_password(userId):
    if request.method == "POST":
            passwd,repasswd = request.form['newPass'],request.form['newRePass']
            if passwd == repasswd:
                new_hashed_value = generate_password_hash(passwd,method='scrypt')
                try:
                    mongo.db.teachers.update_one({'_id':ObjectId(userId)},{"$set":{"passwd":new_hashed_value}})
                    flash("Password Changed!")
                    mongo.db.forgot_users.delete_many({'userId':ObjectId(userId)})
                    return redirect(url_for("teacher.login"))
                except Exception as e:
                    flash(e)
            else:
                flash("Password does not match!")
    return render_template("teacher/resetPassword.html",userId=userId)

@teacher.route("/dashboard",methods=['GET', 'POST'])
def dashboard():
    if check_login():
        return render_template("teacher/dashboard.html",name=session['teacherName'])
    else:
        return redirect(url_for("teacher.login"))

@teacher.route("/logout",methods=['GET', 'POST'])
def logout():
    session.pop('teacherName')
    session.pop('teacher_id')
    return redirect(url_for("teacher.login"))

@teacher.route("/test_details/<testCode>",methods=['GET', 'POST'])
def fetch_test_details(testCode):
    if check_login():
        fetch_testcodes = list(mongo.db.testDetails.find({},{'_id':0,"test_time":0}))
        raw_available_testcodes=[i["test_code"] for i in fetch_testcodes]
        available_testcodes = remove_duplicates(raw_available_testcodes)
        if testCode in available_testcodes:
            test_details = list(mongo.db.testDetails.find({"test_code":testCode},{'_id':0,"test_time":0}))
            fetch_test_questions = list(mongo.db[testCode].find({},{"_id":0,"correct_ans":0}))
            return render_template("teacher/show_questions.html",test_codes=available_testcodes,test_details=test_details,questions=fetch_test_questions)
        return jsonify({"resp":"TESTCODE NOT FOUND"})
    else:
        return redirect(url_for('teacher.login'))

@teacher.route("/show_questions",methods=['GET', 'POST'])
def show_questions():
    if check_login():
        fetch_testcodes = list(mongo.db.testDetails.find({},{'_id':0,"test_time":0}))
        raw_test_codes=[i["test_code"] for i in fetch_testcodes]
        test_codes = remove_duplicates(raw_test_codes)
        fetch_first_test = list(mongo.db.testDetails.find({"test_code":test_codes[0]},{'_id':0,"test_time":0}))
        fetch_test_questions = list(mongo.db[fetch_first_test[0]["test_code"]].find({},{"_id":0,"correct_ans":0}))
        return render_template("teacher/show_questions.html",test_codes=test_codes,test_details=fetch_first_test,questions=fetch_test_questions)
    else:
        return redirect(url_for('teacher.login'))

@teacher.route("/issues/<testCode>",methods=['GET', 'POST'])
def fetch_technical_issues(testCode):
    if check_login():
        fetch_testcodes = list(mongo.db.testDetails.find({},{"test_code":1}))
        raw_available_testcodes=[i["test_code"] for i in fetch_testcodes]
        available_testcodes = remove_duplicates(raw_available_testcodes)
        if testCode in available_testcodes:
            zero_results = list(mongo.db[f"{testCode}-result"].find({"score":0}))
            return render_template("teacher/technical_issues.html",test_codes=available_testcodes,zero_results=zero_results)
        return jsonify({"resp":"TESTCODE NOT FOUND"})
    else:
        return redirect(url_for('teacher.login'))


@teacher.route("/technical_issues",methods=['GET', 'POST'])
def technical_issues():
    if check_login():
        fetch_testcodes = list(mongo.db.testDetails.find({},{"test_code":1}))
        raw_test_codes=[i["test_code"] for i in fetch_testcodes]
        test_codes = remove_duplicates(raw_test_codes)
        zero_results = list(mongo.db[f"{test_codes[0]}-result"].find({"score":0},{}))
        return render_template("teacher/technical_issues.html",test_codes=test_codes,zero_results=zero_results)
    else:
        return redirect(url_for("teacher.login"))

@teacher.route("/delete_result",methods=['GET', 'POST'])
def delete_result():
    if check_login():
        if request.method == "POST":
            obj_id = request.json["obj_id"]
            test_code = request.json["test_code"]
            try:
                mongo.db[f"{test_code}-result"].delete_one({"_id":ObjectId(obj_id)})
                flash("Deleted successfully!")
                return jsonify({"url":f"/teacher/issues/{test_code}"})
            except Exception as e:
                flash(e)
        return redirect(url_for("teacher.technical_issues"))
    else:
        return redirect(url_for("teacher.login"))

@teacher.route("/view_results",methods=['GET', 'POST'])
def view_results():
    if check_login():
        fetch_testcodes = list(mongo.db.testDetails.find({"test_type": {"$ne": "University Exam"}},{'_id':0,"test_time":0}))
        raw_test_codes=[i["test_code"] for i in fetch_testcodes]
        test_codes = remove_duplicates(raw_test_codes)
        try:
            handling_classes = mongo.db.teachers.find_one({"username":session["teacherName"]})["handling_classes"]
            classes = [i[j] for i in handling_classes for j in range(len(i))]
        except:
            classes = []
        if request.method == "POST":
            try:
                user_test_codes = [request.form.get("first_code"),request.form.get("second_code"),request.form.get("third_code"),request.form.get("fourth_code")]
                test_codes = [f'{request.form.get("first_code")}-result',f'{request.form.get("second_code")}-result',f'{request.form.get("third_code")}-result',f'{request.form.get("fourth_code")}-result']
                Class = request.form.get("classes")

src/templates/teacher/dashboard.html
{% extends "teacher/teacher_base.html" %}

{% block title %}Teacher Dashboard{% endblock %}

{% block bodyContent %}
<h1 class="mx-5 mt-5">Welcome, {{name}} !</h1>

<div class="d-flex">
  <div class="card border-warning text-bg-dark mb-3 m-5 text-wrap" style="max-width: 18rem;">
    <h5 class="card-header text-wrap">View testcodes</h5>
    <div class="card-body text-wrap">
      <p class="card-text" style="text-transform:capitalize;">View existing testcodes! <br><br> View existing testcode and its questions</p>
      <a href="{{ url_for('teacher.show_questions') }}" class="btn btn-warning"> View testcodes</a>
    </div>
  </div>

  <div class="card border-warning text-bg-dark mb-3 m-5 text-wrap" style="max-width: 18rem;">
    <h5 class="card-header text-wrap">Technical Issues</h5>
    <div class="card-body text-wrap">
      <p class="card-text" style="text-transform:capitalize;">Review Technical issues! <br><br> View technical issues and resolve it</p>
      <a href="{{ url_for('teacher.technical_issues') }}" class="btn btn-warning"> Review Technical Issues</a>
    </div>
  </div>

  <div class="card border-warning text-bg-dark mb-3 m-5 text-wrap" style="max-width: 18rem;">
    <h5 class="card-header text-wrap">View Results</h5>
    <div class="card-body text-wrap">
      <p class="card-text" style="text-transform:capitalize;">View individual results! <br><br> View individual student results according to your handling classes</p>
      <a href="{{ url_for('teacher.view_results') }}" class="btn btn-warning"> View Results</a>
    </div>
  </div>

  <div class="card border-warning text-bg-dark mb-3 m-5 text-wrap" style="max-width: 18rem;">
    <h5 class="card-header text-wrap">Add Your Handling Classes</h5>
    <div class="card-body text-wrap">
      <p class="card-text" style="text-transform:capitalize;">Add your handling classes! <br><br> Add your current handling classes</p>
      <a href="{{ url_for('teacher.add_handling_classes') }}" class="btn btn-warning">Add Handling Classes</a>
    </div>
  </div>
  
</div>
{% endblock %}

src/templates/teacher/index.html
{% extends "base.html" %}

{% block title %}VEC Quiz App{% endblock %}
{% block bodyContent %}
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{message}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    <div class="ModelBox shadow-lg p-3 mb-5 rounded-3">
        <h3>Teacher Login</h3>
        <form action="{{ url_for('teacher.login')}}" method="POST">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" name="teacherEmail" id="floatingInput" placeholder="Your Email" required>
                <label for="floatingInput">Email</label>
              </div>              
              <div class="form-floating mb-3">
                <input type="password" name="teacherPass" class="form-control" id="floatingInput" placeholder="password" required>
                <label for="floatingInput">Password</label>
              </div>    
            <button type="submit" class="btn btn-lg btn-success">Login</button>
        </form>
            <a href="{{ url_for('teacher.reset_request') }}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover loginLinks "> Forgot your password?</a><br>
    </div>
{% endblock %}

src/templates/teacher/show_questions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Details</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='show_questions.css') }}"> 
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="sidebar">
       <h1 style="color:white">Test Codes</h1>
       <a href="{{ url_for('teacher.dashboard') }}">Go to Dashboard</a>
       {% for testCode in test_codes %}
            <a href="{{ url_for('teacher.fetch_test_details', testCode=testCode) }}" id="testCodes">{{testCode}}</a>
       {% endfor %}
       
    </div>
    <div class="content">
        {% for i in test_details %}
            <div class="test-container shadow p-3 mb-5 bg-body-tertiary rounded">
                <div class="row">
                    <div class="col">
                        <h4 id="test_code">Test Code: {{i["test_code"]}}</h4>
                    </div>
                    <div class="col">
                        <div class="d-flex justify-content-end">
                            <h4 id="audio_name" class="mx-2">Audio Name: {{i["audio_name"]}}</h4>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col">
                        <h4>Lab Session: {{i["lab_session"]}}</h4>
                    </div>
                    
                    <div class="col">
                        <div class="d-flex justify-content-end ">
                            <h4 class="mx-2" id="file_name">Questions file name: {{i["questions_filename"]}}</h4>
                        </div>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col">
                        <h4>Audio No: {{i["audio_no"]}}</h4>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% for question in questions %}
        <div class="questions-box shadow p-3 mb-5 bg-body-tertiary rounded">
            <div class="question-details">
                <h4 id="qno">Question-no: {{question["question_no"]}}</h4>
                <h4 id="qusetion">Question: {{question["question"]}}</h4>
                <h4 id="choice1">Choice 1: {{question["choice1"]}}</h4>
                <h4 id="choice2">Choice 2: {{question["choice2"]}}</h4>
                <h4 id="choice3">Choice 3: {{question["choice3"]}}</h4>
                <h4 id="choice4">Choice 4: {{question["choice4"]}}</h4>
            </div>
        </div>
        {% endfor %} 
    </div>
<script>    
</script>
</body>
</html> 

src/templates/teacher/signup.html
{% extends "base.html" %}
{% block title %}VEC Quiz App{% endblock %}

{% block bodyContent %}
    <br>
    {% for message in get_flashed_messages() %}
    {% if message == "Registered successfully!" %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div> 
    {% endfor %}
    <div class="ModelBox shadow-lg p-3 mb-5 rounded-3">
        <h3>Sign up as a teacher</h3>
        <form action="{{ url_for('teacher.signup') }}" method="POST">
                <select class="form-select form-select-lg mb-3" name="teacherName" id="teacher" aria-label="Teacher Name" required>
                  <option value="Teacher Name" selected disabled>Teacher Name</option>
                  <option value="Baskaran V">Baskaran V</option>
                  <option value="Sugapriya S">Sugapriya S</option>
                  <option value="Balaji A">Balaji A</option>
                  <option value="Latha J">Latha J</option>
                  <option value="Dhanalakshmi R">Dhanalakshmi R</option>
                  <option value="Vinothkumar M">Vinothkumar M</option>
                  <option value="Anand V">Anand V</option>
                  <option value="Archana G.M">Archana G.M</option>
                  <option value="Kirubakaran Amalraj">Kirubakaran Amalraj</option>
                </select>
              <div class="form-floating mb-3">
                <input type="email" class="form-control" name="teacherEmail" id="floatingInput" placeholder="Email" required>
                <label for="floatingInput">Email Address</label>
              </div>
                        
              <div class="form-floating mb-3">
                <input type="password" class="form-control" name="teacherPass" id="floatingInput" placeholder="password" required>
                <label for="floatingInput">Password</label>
              </div>
              <div class="form-floating mb-3">
                <input type="password" class="form-control" name="teacherRePass" id="floatingInput" placeholder="password" required>
                <label for="floatingInput">Confirm Password</label>
              </div> 
            <button type="submit" class="btn btn-lg btn-primary">Register</button>
        </form>
        <a href="{{ url_for('teacher.login') }}" class="link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover loginLinks ">Already have an account? Login here </a><br>
    </div>
{% endblock %}

src/templates/teacher/teacher_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- BootStrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <!-- AJAX -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <!-- BootStrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    {% block customCSS %}{% endblock %}
      
    <link rel="stylesheet" href="{{ url_for('static',filename='admin.css') }}">
</head>
<body>
  {% block customJS %}{% endblock %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Teacher</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{ url_for('teacher.dashboard') }}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('teacher.show_questions') }}">View testcodes</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('teacher.technical_issues') }}">View technical issues</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('teacher.view_results') }}">View Results</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('teacher.add_handling_classes') }}">Add Handling Classes</a>
              </li>
            </ul>
          </div>
          <div class="d-flex justify-content-end">
            <img src="{{ url_for('static',filename='VEC-logo.png') }}" alt="logo" width="75" style="border-radius: 50%;">
          </div>
          <a href="{{ url_for('teacher.logout') }}" class="btn btn-danger">Logout</a>
        </div>
    </nav>
    {% block bodyContent %}{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

src/templates/teacher/technical_issues.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Details</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='show_questions.css') }}">
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    <div class="sidebar">
       <h1 style="color:white; margin: 25px;">Test Codes</h1>
       <a href="{{ url_for('teacher.dashboard') }}"> Go to Dashboard</a>
       {% for testCode in test_codes %}
            <a href="{{ url_for('teacher.fetch_technical_issues', testCode=testCode) }}" id="testCodes">{{testCode}}</a>
       {% endfor %}
    </div>
    <div class="content d-flex align-items-center justify-content-center">

        {% for message in get_flashed_messages() %}
            {% if "successfully" in message %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% else %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    {{message}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
        {% endfor %}

        {% for result in zero_results %}
        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Result ?</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                    <div class="modal-body">
                        <strong class="text-danger">Are you sure to delete this??</strong><br>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal" onclick="sendObjId()">Confirm</button>
                    </div>
            </div>
            </div>
            <script>
                sendObjId=()=>{
                    $.ajax({
                        type:"POST",
                        headers: {"Content-Type": "application/json"},
                        url : "/teacher/delete_result",
                        data: JSON.stringify({"obj_id":"{{result['_id']}}","test_code":"{{result['test_code']}}"}),
                        success: function(response){
                            window.location.href = response.url;
                        }
                    })
                }
            </script>
        </div>


        <div class="questions-box shadow p-3 mb-5 bg-body-tertiary rounded d-flex justify-content-between">
            <div class="question-details">
                <h4 id="qno">Name: {{result["name"]}}</h4>
                <h4 id="qusetion">Regno: {{result["regno"]}}</h4>
                <h4 id="choice1">Class: {{result["class"]}}</h4>
                <h4 id="choice1">Score: {{result["score"]}}</h4>
                <h4 id="choice2">Percentage: {{result["percentage"]}}</h4>
                <h4 id="choice3">Status: {{result["status"]}}</h4>
            </div>
            <div class="">
                <button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
            </div>
        </div>
        {% endfor %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>



</body>
</html>

src/templates/teacher/view_reports.html
{% extends "teacher/teacher_base.html" %}

{% block customCSS %}
<link rel="stylesheet" href="{{ url_for('static',filename='teacher_report.css') }}">
{% endblock %}
{% block title %}Reports{% endblock %}
  
{% block bodyContent %}
  <div class="content">
    <form action="{{ url_for('teacher.view_results') }}" method="post">
      <div class="d-flex justify-content-sm-center align-items-center">
        <div class="d-flex justify-content-sm-start">
          <div class="p-2">
            <select name="test_code" id="test_code" class="form-select" required>
              <option selected disabled>Test Code</option>
              {% for testCode in test_codes %}
                <option value="{{testCode}}">{{ testCode|e }}</option>
              {% endfor %}
            </select>
          </div>
        </div>
        <div class="d-flex justify-content-sm-end p-2 m-2">
          <div class="p-2">
              <select class="form-select" id="class" name="classes" required>
                <option disabled selected>Class</option>
                {% for Class in classes %}
                <option value="{{Class}}">{{Class}}</option>
                {% endfor %}
              </select>
          </div>
          <div class="d-flex justify-content-sm-evenly p-2">
            <button type="submit" class="btn btn-info">Search</button>
          </div>
        </div>
      </div>
    </form>
    <br>

    {% if test_results == [] %}
      <div class="d-flex justify-content-sm-center align-items-center">
        <h3>No Test Results Found for {{Class}}</h3>
      </div>
      <br>
    {% else %}
    <div class="d-flex justify-content-sm-center align-items-center">
      <h3>{{test_code}} Results for {{Class}}</h3>
    </div>
    <br>
    
    <table id="report">
      <tr>
        <th>S.NO</th>
        <th>REG.NO</th>
        <th>NAME</th>
        <th>SCORE</th>          
        <th>PERCENTAGE</th>          
        <th>RESULT</th>          
      </tr>
      {% for i in range(test_results | length) %}
        <tr>
          <td>{{ i+1 }}</td>
          <td>{{ test_results[i]["regno"] }}</td>
          <td>{{ test_results[i]['name'] | upper }}</td>
          <td>{{ test_results[i]['score'] }}</td>
          <td>{{ test_results[i]['percentage'] }}</td>
          <td>{{ test_results[i]['status'] }}</td>
        </tr>
      {% endfor %}
    </table> 
    {% endif %}
   </div>
{% endblock %}